Fixed `unloadable` missing crash
For specifics see sciyoshi/redmine-slack#163

This is meant to address the following error

```
redmine_1  | rake aborted!
redmine_1  | NameError: undefined local variable or method `unloadable' for class Issue (NameError)
redmine_1  | /usr/local/bundle/gems/activerecord-7.2.2.1/lib/active_record/dynamic_matchers.rb:22:in `method_missing'
redmine_1  | /usr/src/redmine/plugins/redmine_slack/lib/redmine_slack/issue_patch.rb:8:in `block in included'
redmine_1  | /usr/src/redmine/plugins/redmine_slack/lib/redmine_slack/issue_patch.rb:7:in `class_eval'
redmine_1  | /usr/src/redmine/plugins/redmine_slack/lib/redmine_slack/issue_patch.rb:7:in `included'
redmine_1  | /usr/src/redmine/plugins/redmine_slack/init.rb:29:in `include'
redmine_1  | /usr/src/redmine/plugins/redmine_slack/init.rb:29:in `block in <top (required)>'
redmine_1  | /usr/local/bundle/gems/activesupport-7.2.2.1/lib/active_support/lazy_load_hooks.rb:94:in `block in execute_hook'
redmine_1  | /usr/local/bundle/gems/activesupport-7.2.2.1/lib/active_support/lazy_load_hooks.rb:87:in `with_execution_control'
redmine_1  | /usr/local/bundle/gems/activesupport-7.2.2.1/lib/active_support/lazy_load_hooks.rb:92:in `execute_hook'
redmine_1  | /usr/local/bundle/gems/activesupport-7.2.2.1/lib/active_support/lazy_load_hooks.rb:78:in `block in run_load_hooks'
redmine_1  | /usr/local/bundle/gems/activesupport-7.2.2.1/lib/active_support/lazy_load_hooks.rb:77:in `each'
redmine_1  | /usr/local/bundle/gems/activesupport-7.2.2.1/lib/active_support/lazy_load_hooks.rb:77:in `run_load_hooks'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/application/finisher.rb:94:in `block in <module:Finisher>'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/initializable.rb:32:in `instance_exec'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/initializable.rb:32:in `run'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/initializable.rb:61:in `block in run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/initializable.rb:60:in `run_initializers'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/application.rb:435:in `initialize!'
redmine_1  | /usr/src/redmine/config/environment.rb:16:in `<top (required)>'
redmine_1  | /usr/local/bundle/gems/zeitwerk-2.7.2/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/application.rb:411:in `require_environment!'
redmine_1  | /usr/local/bundle/gems/railties-7.2.2.1/lib/rails/application.rb:559:in `block in run_tasks_blocks'
redmine_1  | /usr/local/bundle/gems/rake-13.2.1/exe/rake:27:in `<top (required)>'
redmine_1  | Tasks: TOP => db:migrate => db:load_config => environment
redmine_1  | (See full trace by running task with --trace)
```